# Generated by stubloom. Do not edit; run `stubloom generate` after changing the Rust.

from typing import Any, ClassVar, final

class CigarError(HGVSError): ...
class DataProviderError(HGVSError): ...

@final
class EquivalenceLevel:
    Analogous: ClassVar[EquivalenceLevel]
    Different: ClassVar[EquivalenceLevel]
    Identity: ClassVar[EquivalenceLevel]
    Unknown: ClassVar[EquivalenceLevel]
    def __eq__(self, value: object) -> bool: ...
    def __hash__(self) -> int: ...

class HGVSError(Exception): ...

@final
class IdentifierType:
    GeneSymbol: ClassVar[IdentifierType]
    GenomicAccession: ClassVar[IdentifierType]
    ProteinAccession: ClassVar[IdentifierType]
    TranscriptAccession: ClassVar[IdentifierType]
    Unknown: ClassVar[IdentifierType]
    def __eq__(self, value: object) -> bool: ...
    def __hash__(self) -> int: ...

class ParseError(HGVSError): ...

@final
class StartCodonConvention:
    """
    Controls how start-codon protein variants are represented.

    Used in VariantTransformSettings to select between keeping the specific
    predicted amino acid change or using the HGVS p.Met1? notation.
    """

    HgvsQuestion: ClassVar[StartCodonConvention]
    """Use the HGVS `p.Met1?` notation for any non-silent change at the first codon."""
    Specific: ClassVar[StartCodonConvention]
    """Keep the specific predicted amino acid change (e.g., `p.(Met1Val)`). Default."""
    def __eq__(self, value: object) -> bool: ...
    def __hash__(self) -> int: ...

class TranscriptMismatchError(HGVSError): ...
class UnsupportedOperationError(HGVSError): ...
class ValidationError(HGVSError): ...

@final
class Variant:
    """
    Represents a parsed HGVS variant.

    Provides access to the variant's accession, gene symbol, and coordinate type.
    Variants can be formatted back to HGVS strings or converted to JSON/dict representations.
    """
    @property
    def ac(self) -> str:
        """The primary accession of the variant (e.g., 'NM_000051.3')."""
    @property
    def coordinate_type(self) -> str:
        """The coordinate type of the variant ('g', 'c', 'p', etc.)."""
    def format(self) -> str:
        """Formats the variant back into a standard HGVS string."""
    @staticmethod
    def from_dict(d: Any) -> Variant:
        """
        Constructs a Variant from a dictionary produced by to_dict.

        Args:
            d: A dict with the same structure as returned by to_dict.

        Returns:
            A Variant object.

        Raises:
            ValueError: If the dict cannot be deserialised into a valid variant.
        """
    @property
    def gene(self) -> str | None:
        """The gene symbol associated with the variant, if available."""
    def to_dict(self) -> Any:
        """Returns a dictionary representation of the internal variant structure."""
    def to_json(self) -> str:
        """Returns a JSON string representation of the internal variant structure."""
    def transform(self, settings: VariantTransformSettings) -> Variant:
        """
        Returns a new variant with the given transform settings applied.

        Currently transforms protein variants according to the start_codon convention.
        All other variant types are returned unchanged.

        Args:
            settings: A VariantTransformSettings object.

        Returns:
            A new Variant with the settings applied.
        """
    def validate(self, provider: Any) -> bool:
        """
        Validates the variant's reference sequence against the provided DataProvider.

        Args:
            provider: The data provider instance for sequence retrieval.

        Returns:
            True if the reference sequence matches, False otherwise.

        Raises:
            ValidationError: If transcript sequence is too short or coordinates are out of bounds.
            DataProviderError: If sequence data cannot be retrieved.
        """

@final
class VariantMapper:
    """
    High-level variant mapping engine.

    Coordinates mapping between different reference sequences (e.g., g. to c.)
    and projects cDNA variants onto protein sequences (c. to p.).
    Requires a DataProvider to retrieve transcript and sequence information.
    """
    def __new__(cls, provider: Any) -> VariantMapper:
        """Creates a new VariantMapper with the given DataProvider."""
    def c_to_g(self, var_c: Variant, reference_ac: str | None = ...) -> Variant:
        """
        Maps a coding cDNA variant (c.) to a genomic variant (g.).

        Args:
            var_c: The coding Variant to map.
            reference_ac: Optional chromosomal accession. If not provided, the primary chromosome for the transcript
        will be used.

        Returns:
            A new Variant object in 'g.' coordinates.

        Raises:
            ValueError: If var_c is not a coding variant.
            HGVSError: If mapping fails due to data or alignment issues.
        """
    def c_to_p(self, var_c: Variant, protein_ac: str | None = ...) -> Variant:
        """
        Projects a coding cDNA variant (c.) or an RNA variant (r.) to its protein consequence (p.).

        An r. variant is predicted from its c. spelling; a statement about the
        transcript (r.0, r.spl, r.?, r.=) becomes the matching statement about the
        protein (p.0, p.?, p.(=)).

        Args:
            var_c: The coding or RNA Variant to project.
            protein_ac: Optional protein accession. If not provided, it will be retrieved from the DataProvider.

        Returns:
            A new Variant object in 'p.' coordinates.

        Raises:
            ValueError: If var_c is not a coding or RNA variant.
            HGVSError: If projection fails due to data retrieval or out-of-bounds coordinates.
        """
    def equivalent(self, var1: Variant, var2: Variant, searcher: Any) -> bool:
        """
        Determines if two variants are biologically equivalent.

        Handles normalization, cross-coordinate mapping (g. vs c.), and gene symbol expansion.

        Args:
            var1: The first Variant object.
            var2: The second Variant object.
            searcher: An object implementing the TranscriptSearch protocol.

        Returns:
            True if the variants are equivalent, False otherwise.

        Raises:
            HGVSError: If mapping, normalization, or data retrieval fails during equivalence checks.
        """
    def equivalent_level(self, var1: Variant, var2: Variant, searcher: Any) -> EquivalenceLevel:
        """
        Determines the granular equivalence level of two variants.

        Args:
            var1: The first Variant object.
            var2: The second Variant object.
            searcher: An object implementing the TranscriptSearch protocol.

        Returns:
            An EquivalenceLevel enum value.

        Raises:
            HGVSError: If mapping, normalization, or data retrieval fails during equivalence checks.
        """
    def g_to_c(self, var_g: Variant, transcript_ac: str) -> Variant:
        """
        Maps a genomic variant (g.) to a coding cDNA variant (c.) for a specific transcript.

        Args:
            var_g: The genomic Variant to map.
            transcript_ac: The accession of the target transcript.

        Returns:
            A new Variant object in 'c.' coordinates.

        Raises:
            ValueError: If var_g is not a genomic variant.
            HGVSError: If mapping fails due to data or alignment issues.
        """
    def g_to_c_all(self, var_g: Variant, searcher: Any) -> list[Variant]:
        """
        Maps a genomic variant (g.) to all overlapping transcripts discovered via the searcher.

        Args:
            var_g: The genomic Variant to map.
            searcher: An object implementing the TranscriptSearch protocol.

        Returns:
            A list of Variant objects in 'c.' coordinates.

        Raises:
            ValueError: If var_g is not a genomic variant.
            HGVSError: If mapping fails due to data or alignment issues.
        """
    def n_to_g(self, var_n: Variant, reference_ac: str | None = ...) -> Variant:
        """
        Maps a non-coding cDNA variant (n.) to a genomic variant (g.).

        Args:
            var_n: The non-coding Variant to map.
            reference_ac: Optional chromosomal accession.

        Returns:
            A new Variant object in 'g.' coordinates.

        Raises:
            ValueError: If var_n is not a non-coding variant.
            HGVSError: If mapping fails due to data or alignment issues.
        """
    def r_to_g(self, var_r: Variant, reference_ac: str | None = ...) -> Variant:
        """
        Maps an RNA variant (r.) to a genomic variant (g.).

        Only a change within one exon has a genomic form; one spanning a splice
        junction describes the spliced RNA and raises UnsupportedOperationError.

        Args:
            var_r: The RNA Variant to map.
            reference_ac: Optional chromosomal accession.

        Raises:
            ValueError: If var_r is not an RNA variant.
            HGVSError: If mapping fails.
        """
    def r_to_c(self, var_r: Variant) -> Variant:
        """
        Respells an RNA variant (r.) as the coding variant (c.) it is numbered from.

        r. positions on a coding transcript are c. positions; the bases become
        uppercase DNA letters (u to T).

        Raises:
            ValueError: If var_r is not an RNA variant.
            HGVSError: If the transcript has no CDS, or the variant is a statement
                about the transcript (r.0, r.spl).
        """
    def r_to_n(self, var_r: Variant) -> Variant:
        """
        Respells an RNA variant (r.) on a non-coding transcript as the n. variant it is numbered from.

        Raises:
            ValueError: If var_r is not an RNA variant.
            HGVSError: If the transcript has a CDS (use r_to_c), or the variant is a
                statement about the transcript.
        """
    def c_to_r(self, var_c: Variant) -> Variant:
        """
        Respells a coding variant (c.) as an RNA variant (r.): the same positions,
        bases in lowercase RNA letters (T to u).

        Raises:
            ValueError: If var_c is not a coding variant.
        """
    def n_to_r(self, var_n: Variant) -> Variant:
        """
        Respells a non-coding variant (n.) as an RNA variant (r.): the same positions,
        bases in lowercase RNA letters (T to u).

        Raises:
            ValueError: If var_n is not a non-coding variant.
        """
    def normalize_variant(self, var: Variant) -> Variant:
        """
        Normalizes a variant by shifting it to its 3'-most position.

        Normalization is performed in the coordinate space of the input variant.

        Args:
            var: The Variant object to normalize.

        Returns:
            A new normalized Variant object.

        Raises:
            HGVSError: If normalization fails due to reference sequence boundaries.
        """
    def p_to_c(self, var_p: Variant, transcript_ac: str | None = ...) -> tuple[Variant, bool]:
        """
        Back-converts a protein substitution (p.) to a coding variant (c.).

        Currently handles single amino acid substitutions only. When multiple codons
        could produce the target amino acid, the one requiring the fewest nucleotide
        changes is chosen.

        Args:
            var_p: The protein Variant to back-convert.
            transcript_ac: Optional transcript accession (NM_). Required if the DataProvider cannot resolve NP to NM.

        Returns:
            A tuple of (Variant in 'c.' coordinates, is_unique: bool).
            is_unique is True if the back-conversion is unambiguous.

        Raises:
            ValueError: If var_p is not a protein variant.
            HGVSError: If back-conversion fails due to unsupported consequence or missing transcript.
        """
    def to_spdi(self, var: Variant, unambiguous: bool = ...) -> str:
        """
        Converts a variant to a SPDI string format.

        Args:
            var: The Variant object to convert.
            unambiguous: If True, expands the variant range to cover the entire ambiguous region of a repeat or
        homopolymer. Default is False.

        Returns:
            A string representing the variant in SPDI format.

        Raises:
            HGVSError: If the variant type cannot be converted to SPDI or sequence data is unavailable.
        """
    def to_spdi_unambiguous(self, var: Variant) -> str:
        """
        Converts a variant to an unambiguous SPDI string format.

        This format is independent of specific shifting conventions (like 3' or 5' shifting)
        by expanding the variant range to cover the entire ambiguous region of a repeat or homopolymer.

        Args:
            var: The Variant object to convert.

        Returns:
            A string representing the variant in unambiguous SPDI format.

        Raises:
            HGVSError: If the variant type cannot be converted to SPDI or sequence data is unavailable.
        """

    def to_vrs(self, var: Variant) -> dict[str, Any]:
        """Returns the GA4GH VRS 2.0 Allele for a variant as a dict.

        A nucleotide variant is projected to its genomic reference; a protein
        variant stays on its protein. Either is canonicalised (fully justified
        over its region of ambiguity) and rendered with computed identifiers. The sequence is identified by its refget accession, taken from
        the DataProvider's optional get_refget_accession or computed from the whole
        sequence.

        Args:
            var: A g., m., c., n. or p. Variant. Protein variants must describe a
                sequence: frameshifts, extensions and p.? have no allele. A g. or
                m. deletion with uncertain breakpoints, g.(?_100)_(200_?)del, is
                rendered as given, with Range bounds ([min, max], null when
                unbounded) and an empty literal state; it is not normalised.

        Returns:
            A dict in the VRS 2.0 Allele schema.

        Raises:
            HGVSError: If the variant cannot be resolved against the reference.
        """

    def vrs_id(self, var: Variant) -> str:
        """Returns the GA4GH VRS computed identifier (ga4gh:VA.<digest>) of a variant.

        Two variants describing the same change on the same sequence have the same
        identifier.

        Args:
            var: A g., m., c., n. or p. Variant. Protein variants must describe a
                sequence: frameshifts, extensions and p.? have no allele.

        Raises:
            HGVSError: If the variant cannot be resolved against the reference.
        """
    def __new__(cls, start_codon: StartCodonConvention = ...) -> VariantTransformSettings:
        """
        Creates a new VariantTransformSettings.

        Args:
            start_codon: Convention for start-codon protein variants. Defaults to Specific.
        """
    @property
    def start_codon(self) -> StartCodonConvention: ...

    def from_vrs(self, allele: dict[str, Any] | str, accession: str | None = None) -> Variant:
        """Returns the Variant a GA4GH VRS 2.0 Allele names.

        The variant is written in HGVS on the allele's own sequence, trimmed to the
        change and normalised (3'-shifted): g. for a nucleotide sequence, p. for a
        protein. Literal and ReferenceLengthExpression states are read; Range bounds
        are accepted for a deletion, which comes back as g.(a_b)_(c_d)del.

        The sequence behind the allele's refget accession is named by ``accession``
        when given, else looked up through the DataProvider's optional
        get_accession_for_refget; the digest is checked against the sequence either
        way.

        Args:
            allele: The Allele as a dict (as to_vrs returns) or a JSON string.
            accession: The accession of the sequence, when the provider cannot look
                it up from the refget accession.

        Raises:
            HGVSError: If the allele is malformed, unsupported, or does not match the
                sequence.
        """

    def from_spdi(self, spdi: str) -> Variant:
        """Returns the Variant an SPDI string names.

        ``accession:position:deletion:insertion`` with an interbase position and the
        deletion given as bases or as a length. The variant is written in HGVS on
        the accession's own sequence, trimmed to the change and normalised
        (3'-shifted): g. for a nucleotide sequence, p. for a protein.

        Args:
            spdi: The SPDI string.

        Raises:
            HGVSError: If the string is malformed or the deletion does not match the
                sequence.
        """

@final
class VariantTransformSettings:
    """
    Settings that control how a variant is transformed before formatting or comparison.

    Create with keyword arguments:
        settings = VariantTransformSettings(start_codon=StartCodonConvention.HgvsQuestion)
    """
def parse(input: str) -> Variant:
    """
    Parses an HGVS string into a Variant object.

    Supported types include genomic (g.), coding cDNA (c.), non-coding (n.),
    mitochondrial (m.), and protein (p.) variants.

    Args:
        input: The HGVS string to parse.

    Returns:
        A Variant object.

    Raises:
        ParseError: If the HGVS string is malformed or unsupported.
    """
